version: "3.9"

services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ee:latest
    restart: unless-stopped
    ports:
      - 8000:8000
      - 9443:9443
    environment:
      - PUID=$PUID
      - PGID=$GUID
      - TZ=$TZ
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - $VOLUMEDIR/portainer:/data