# Network specifications
networks:
  unifi:
    driver: macvlan
    driver_opts:
      parent: ens18
    ipam:
      config:
        - subnet: 10.28.1.0/24
          ip_range: 10.28.1.240/32
          gateway: 10.28.1.1