global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v1
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
    - targets:
      - localhost:9990
      - pve1.nickeson.net:9100 # node-exporter
      - pve2.nickeson.net:9100 # node-exporter
      - pbs.nickeson.net:9100 # node-exporter
      - gateway.nickeson.net:9798 # speedtest-exporter
- job_name: vyos
  scrape_interval: 1m
  scrape_timeout: 10s
  honor_timestamps: true
  static_configs:
    - targets:
        - vyos.nickeson.net:9273
