---
- hosts: proxmox
  become: true
  pre_tasks:
    - name: Update apt packages
      apt:
        update_cache: true
        cache_valid_time: 86400
        upgrade: true

    - name: Install packages
      apt:
        name:
          - jq
          - git
          - lm-sensors
          - ncdu
          - vim
        state: present

  roles:
    - name: Security hardening
      role: kencx.ansible.security
      vars:
        - ssh_disable_root_login: true
        - ufw_rules:
            - {rule: 'allow', port: '22', proto: 'tcp', comment: 'ssh'}
            - {rule: 'allow', port: '53', proto: 'tcp', comment: 'dns'}
            - {rule: 'allow', port: '53', proto: 'udp', comment: 'dns'}
            - {rule: 'allow', port: '4000', proto: 'tcp', comment: 'blocky http'}
    - role: coredns
    - role: blocky
      vars:
        blocky_client_lookup:
          upstream: 192.168.86.1
          clients:
            arch:
              - 192.168.86.82
            pixel:
              - 192.168.86.20
# TODO add static route to access private subnet
