version: "3.9"

#networks:
#  default:
#    driver: bridge

services:
  redis:
    image: redis
    restart: always
    env_file: ./outline.env
    #ports:
    #  - "6379:6379"
    volumes:
      - $VOLUMEDIR/appdata/redis:/redis.conf
    command: ["redis-server", "/redis.conf"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 3

  postgres-outline:
    image: postgres
    restart: always
    env_file: ./outline.env
    #ports:
    #  - "5432:5432"
    volumes:
      - $VOLUMEDIR/postgres-outline:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      POSTGRES_USER: 'outline'
      POSTGRES_PASSWORD: 'V8RejsGNhi4E7ol'
      POSTGRES_DB: 'outline'

  outline:
    image: docker.getoutline.com/outlinewiki/outline:latest
    restart: always
    env_file: ./outline.env
    ports:
      - "5000:3000"
    depends_on:
      - postgres-outline
      - redis

