version: "3.9"

networks:
  default:
    driver: bridge

########################### SECRETS
secrets:
  SONARR__API_KEY:
    file: $SECRETSDIR/SONARR_API_KEY
  RADARR__API_KEY:
    file: $SECRETSDIR/RADARR_API_KEY

services:

  radarr:
    container_name: radarr
    image: cr.hotio.dev/hotio/radarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 7878:7878
    environment:
      - PUID=$PUID
      - PGID=$GUID
      - TZ=$TZ
      - RADARR__API_KEY=/run/secrets/RADARR_API_KEY
    secrets:
      - RADARR__API_KEY
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $VOLUMEDIR/radarr:/config
      - /media:/media
      - /downloads:/downloads
  sonarr:
    container_name: sonarr
    image: cr.hotio.dev/hotio/sonarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 8989:8989
    environment:
      - PUID=$PUID
      - PGID=$GUID
      - TZ=$TZ
      - SONARR__API_KEY=/run/secrets/SONARR_API_KEY
    secrets:
      - SONARR__API_KEY
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $VOLUMEDIR/sonarr:/config
      - /media:/media
      - /downloads:/downloads
  lidarr:
    container_name: lidarr
    image: ghcr.io/hotio/lidarr
    restart: unless-stopped
    ports:
      - "8686:8686"
    environment:
      - PUID=$PUID
      - PGID=$GUID
      - TZ=$TZ
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $VOLUMEDIR/lidarr:/config
      - /media:/media
      - /downloads:/downloads

  readarr:
    container_name: readarr
    image: ghcr.io/hotio/readarr
    ports:
      - "8787:8787"
    environment:
      - PUID=$PUID
      - PGID=$GUID
      - UMASK=002
      - TZ=$TZ
    volumes:
      - $VOLUMEDIR/readarr:/config
      - /media:/media
      - /downloads:/downloads

  bazarr:
    container_name: bazarr
    image: cr.hotio.dev/hotio/bazarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 6767:6767
    environment:
      - PUID=$PUID
      - PGID=$GUID
      - TZ=$TZ
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $VOLUMEDIR/bazarr:/config
      - /media:/media
  sabnzbd:
    container_name: sabnzbd
    image: cr.hotio.dev/hotio/sabnzbd:latest
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 8080:8080
      - 9091:9090
    environment:
      - PUID=$PUID
      - PGID=$GUID
      - TZ=$TZ
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $VOLUMEDIR/sabnzbd:/config
      - /media:/media
      - /downloads:/downloads
  prowlarr:
    container_name: prowlarr
    image: ghcr.io/hotio/prowlarr:latest
    restart: unless-stopped
    ports:
      - "9696:9696"
    environment:
      - PUID=$PUID
      - PGID=$GUID
      - TZ=$TZ
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $VOLUMEDIR/prowlarr:/config

  overseerr:
    container_name: overseerr
    image: ghcr.io/hotio/overseerr
    restart: unless-stopped
    ports:
      - "5055:5055"
    environment:
      - PUID=$PUID
      - PGID=$GUID
      - TZ=$TZ
    volumes:
      - $VOLUMEDIR/overseerr:/config

  recyclarr:
    image: ghcr.io/recyclarr/recyclarr
    restart: unless-stopped
    container_name: recyclarr
    user: $PUID:$GUID
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $VOLUMEDIR/recyclarr:/config
    environment:
      - TZ=$TZ