[book]
title = "Infra Documentation"
authors = ["fisherbln"]
language = "en"
multilingual = false
src = "src"

[output.html]
git-repository-url = "https://github.com/fisherbln/infra"
no-section-label = true

[output.html.fold]
enable = true
level = 1
