version: "3.9"

secrets:
  GF_SECURITY_ADMIN_PASSWORD:
    file: $SECRETSDIR/GF_SECURITY_ADMIN_PASSWORD
  GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET:
    file: $SECRETSDIR/GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    ports:
      - 9990:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - $VOLUMEDIR/prometheus:/prometheus
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 4000:3000
    restart: unless-stopped
    env_file:
      - grafana.env
    environment:
      - GF_SERVER_ROOT_URL=https://grafana.nickeson.net
      - GF_SECURITY_ADMIN_USER=admin
      #GF_SECURITY_ADMIN_PASSWORD: grafana
      - GF_SECURITY_ADMIN_PASSWORD__FILE=/run/secrets/GF_SECURITY_ADMIN_PASSWORD
      - GF_AUTH_GENERIC_OAUTH_CLIENT_ID=grafana
      - GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET__FILE=/run/secrets/GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
      - GF_AUTH_GENERIC_OAUTH_AUTH_URL=https://auth.nickeson.net/api/oidc/authorization
      - GF_AUTH_GENERIC_OAUTH_TOKEN_URL=https://auth.nickeson.net/api/oidc/token
      - GF_AUTH_GENERIC_OAUTH_API_URL=https://auth.nickeson.net/api/oidc/userinfo

  
    secrets:
      - GF_SECURITY_ADMIN_PASSWORD
      - GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
    volumes:
      #- ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana:/etc/grafana/
#volumes:
#  prom_data:
