version: "3.9"

secrets:
  GF_SECURITY_ADMIN_PASSWORD:
    file: $SECRETSDIR/GF_SECURITY_ADMIN_PASSWORD

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    ports:
      - 9990:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - $VOLUMEDIR/prometheus:/prometheus
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 4000:3000
    restart: unless-stopped
    env_file:
      - grafana.env
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: grafana
      #GF_SECURITY_ADMIN_PASSWORD: /run/secrets/GF_SECURITY_ADMIN_PASSWORD
  
    secrets:
      - GF_SECURITY_ADMIN_PASSWORD
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
#volumes:
#  prom_data:
